"""empty message

Revision ID: 8c3af76b12ce
Revises: 
Create Date: 2023-01-06 20:46:02.578236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c3af76b12ce'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('gender')

    op.create_table('pet',
    sa.Column('name', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('owner', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('species', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('sex', mysql.CHAR(length=1), nullable=True),
    sa.Column('birth', sa.DATE(), nullable=True),
    sa.Column('death', sa.DATE(), nullable=True),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
